Fixed a couple of bugs
henkelmax/gravestone pull request #5
Opened 2020-09-01 23:01 UTC by gekkone

The name of the lower world was displayed incorrectly in the obituary
Death note was not deleted when the remove_death_note option was enabled due to an error in getting dimension

2020-09-02 08:29 UTC, henkelmax requested changes

2020-09-02 08:29 UTC, henkelmax commented on src/main/java/de/maxhenkel/gravestone/events/BlockEvents.java
> +        String dim = player.world.func_230315_m_().func_240901_a_().toString();
This function does not exist

2020-09-04 20:47 UTC, gekkone commented
Correcting a typo

2020-09-05 07:28 UTC, henkelmax approved these changes

2020-09-05 07:28 UTC, merged

2020-09-05 07:29 UTC, henkelmax commented
Thank you!
The update should be out soon.